---
# provision a kubernetes master from localhost
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../vars.yml"
    - "{{ playbook_dir }}/../vars_aws.yml"
  vars:
    packages:
      - "{{bucket_base_path}}/etcd/etcd-{{ version.etcd }}-linux-amd64.tar.gz"
      - "{{bucket_base_path}}/docker-distribution/docker-distribution-{{ version.registry }}-linux-amd64.tar.gz"
      - "{{bucket_base_path}}/kubernetes/kubernetes-server-{{ version.kubernetes }}-linux-amd64.tar.gz"
  connection: local
  gather_facts: no
  tasks:
    - name: create kubernetes master
      ec2:
        instance_type: "{{ instance_type.cluster }}"
        image: "{{ image_id }}"
        vpc_subnet_id: "{{ subnet_id.cluster }}"
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        instance_profile_name: "{{ instance_profile_name }}"
        group_id:
          - "{{ sg_id.cluster }}"
          - "{{ sg_id.master }}"
        termination_protection: no
        wait: yes
        volumes:
          - "{{ root_volume }}"
        instance_tags:
          Name: "{{ app_name }}-master"
          Role: master
          App: "{{ app_name }}"
        user_data: "{{ user_data }}"
      register: ec2

    - name: update vars file
      lineinfile:
        path: "{{ playbook_dir }}/../hosts"
        insertafter: 'master'
        line: "{{ item.private_ip }}  # master ANSIBLE_MANAGED"
      with_items: "{{ ec2.instances }}"

    - name: print instance details
      debug:
        msg: "master - {{ item.id }} / {{ item.private_ip }}"
      with_items: "{{ ec2.instances }}"
