---
# configure elb from localhost
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../vars.yml"
    - "{{ playbook_dir }}/../vars_aws.yml"
  connection: local
  gather_facts: no
  tasks:
    - name: get node instances
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "vpc-id": "{{ vpc_id }}"
          "tag:App": "{{ app_name }}"
          "tag:Role": node
      register: ec2_nodes

    - name: add instances to elb
      elb_instance:
        ec2_elbs: "{{ elb_name }}"
        state: present
        region: "{{ region }}"
        instance_id: "{{ item.instance_id }}"
      with_items: "{{ ec2_nodes.instances }}"
