---
# authorize public IP in security groups from localhost
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../vars.yml"
    - "{{ playbook_dir }}/../vars_aws.yml"
  connection: local
  gather_facts: no
  tasks:
    - name: get public IP
      ipify_facts:

    - name: update bastion SG
      ec2_group:
        name: "{{ app_name }}-bastion"
        description: "{{ app_name }}-bastion"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: icmp
            from_port: -1
            to_port: -1
            cidr_ip: "{{ ipify_public_ip }}/32"
          - proto: tcp
            cidr_ip: "{{ ipify_public_ip }}/32"
            ports:
              - 22
              - 80
